### ISSUE TITLE
New release containing `1f305d0d98db76a570039898ea36d5e72b556dca`

### ISSUE THREAD

**Issue by trhodeos** [gotosleep/Xoogler#2]
Hey @gotosleep, no rush here, but when you get the chance, would you mind releasing the extension from master? Thanks!

**Comment by gotosleep** [comment]
Hey, wanted to let you know that I submitted a new version to the chrome
webstore containing support for your %s change. It might take a few days to
a few weeks for the release to be reviewed and approved. Thanks again for
your help!

**Comment by trhodeos** [comment]
Thanks!
